/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Venice } from "@fern-api/venice";

export interface UpdateResource {
    id?: string;
    creatorId?: string;
    integrationId?: string;
    institutionId?: string;
    envName?: string;
    settings?: string;
    createdAt?: string;
    updatedAt?: string;
    providerName?: string;
    displayName?: string;
    /**
     * Preference
     */
    prefer?: Venice.Return;
    body: Venice.Resource;
}
