/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import { Venice } from "@fern-api/venice";
import urlJoin from "url-join";
import * as core from "../../../../core";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace TransactionSplit {
    interface Options {
        environment: environments.VeniceEnvironment | string;
    }
}

export class TransactionSplit {
    constructor(private readonly options: TransactionSplit.Options) {}

    /**
     *   Entities description that
     *   spans
     *   multiple lines
     *
     *
     * 	@graphql({
     * 		"primary_key_columns": ["id", "key"],
     * 		"totalCount": {"enabled": true},
     * 		"foreign_keys": []
     * 	})
     *
     */
    public async get(request: Venice.GetTransactionSplit = {}): Promise<Venice.TransactionSplit[]> {
        const {
            transactionId,
            key,
            amountQuantity,
            amountUnit,
            accountId,
            data,
            updatedAt,
            createdAt,
            select,
            order,
            offset,
            limit,
            range,
            rangeUnit,
            prefer,
        } = request;
        const _queryParams = new URLSearchParams();
        if (transactionId != null) {
            _queryParams.append("transaction_id", transactionId);
        }

        if (key != null) {
            _queryParams.append("key", key);
        }

        if (amountQuantity != null) {
            _queryParams.append("amount_quantity", amountQuantity);
        }

        if (amountUnit != null) {
            _queryParams.append("amount_unit", amountUnit);
        }

        if (accountId != null) {
            _queryParams.append("account_id", accountId);
        }

        if (data != null) {
            _queryParams.append("data", data);
        }

        if (updatedAt != null) {
            _queryParams.append("updated_at", updatedAt);
        }

        if (createdAt != null) {
            _queryParams.append("created_at", createdAt);
        }

        if (select != null) {
            _queryParams.append("select", select);
        }

        if (order != null) {
            _queryParams.append("order", order);
        }

        if (offset != null) {
            _queryParams.append("offset", offset);
        }

        if (limit != null) {
            _queryParams.append("limit", limit);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/transaction_split"),
            method: "GET",
            headers: {
                Range: range,
                "Range-Unit": rangeUnit,
                Prefer: prefer,
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.transactionSplit.get.Response.parseOrThrow(
                _response.body as serializers.transactionSplit.get.Response.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
