/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class VeniceTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, VeniceTimeoutError.prototype);
    }
}
