/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Venice } from "@fern-api/venice";

export interface GetPipeline {
    id?: string;
    sourceId?: string;
    sourceState?: string;
    destinationId?: string;
    destinationState?: string;
    linkOptions?: string;
    createdAt?: string;
    updatedAt?: string;
    lastSyncStartedAt?: string;
    lastSyncCompletedAt?: string;
    /**
     * Filtering Columns
     */
    select?: string;
    /**
     * Ordering
     */
    order?: string;
    /**
     * Limiting and Pagination
     */
    offset?: string;
    /**
     * Limiting and Pagination
     */
    limit?: string;
    /**
     * Limiting and Pagination
     */
    range?: string;
    /**
     * Limiting and Pagination
     */
    rangeUnit?: string;
    /**
     * Preference
     */
    prefer?: Venice.Count;
}
