/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import { Venice } from "@fern-api/venice";
import urlJoin from "url-join";
import * as core from "../../../../core";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Transaction {
    interface Options {
        environment: environments.VeniceEnvironment | string;
    }
}

export class Transaction {
    constructor(private readonly options: Transaction.Options) {}

    /**
     * @graphql({
     * 	"primary_key_columns": ["id"],
     * 	"totalCount": {"enabled": true},
     * 	"description": "Double entry transaction",
     * 	"foreign_keys": [
     * 		{
     *       "local_name": "transactions",
     *       "local_columns": ["account_id"],
     *       "foreign_name": "account",
     *       "foreign_schema": "public",
     *       "foreign_table": "account",
     *       "foreign_columns": ["id"]
     * 		}
     * 	]
     * })
     */
    public async get(request: Venice.GetTransaction = {}): Promise<Venice.Transaction[]> {
        const {
            id,
            date,
            description,
            payee,
            amountQuantity,
            amountUnit,
            accountId,
            externalCategory,
            notes,
            splits,
            external,
            updatedAt,
            createdAt,
            select,
            order,
            offset,
            limit,
            range,
            rangeUnit,
            prefer,
        } = request;
        const _queryParams = new URLSearchParams();
        if (id != null) {
            _queryParams.append("id", id);
        }

        if (date != null) {
            _queryParams.append("date", date);
        }

        if (description != null) {
            _queryParams.append("description", description);
        }

        if (payee != null) {
            _queryParams.append("payee", payee);
        }

        if (amountQuantity != null) {
            _queryParams.append("amount_quantity", amountQuantity);
        }

        if (amountUnit != null) {
            _queryParams.append("amount_unit", amountUnit);
        }

        if (accountId != null) {
            _queryParams.append("account_id", accountId);
        }

        if (externalCategory != null) {
            _queryParams.append("external_category", externalCategory);
        }

        if (notes != null) {
            _queryParams.append("notes", notes);
        }

        if (splits != null) {
            _queryParams.append("splits", splits);
        }

        if (external != null) {
            _queryParams.append("external", external);
        }

        if (updatedAt != null) {
            _queryParams.append("updated_at", updatedAt);
        }

        if (createdAt != null) {
            _queryParams.append("created_at", createdAt);
        }

        if (select != null) {
            _queryParams.append("select", select);
        }

        if (order != null) {
            _queryParams.append("order", order);
        }

        if (offset != null) {
            _queryParams.append("offset", offset);
        }

        if (limit != null) {
            _queryParams.append("limit", limit);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/transaction"),
            method: "GET",
            headers: {
                Range: range,
                "Range-Unit": rangeUnit,
                Prefer: prefer,
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.transaction.get.Response.parseOrThrow(
                _response.body as serializers.transaction.get.Response.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * @graphql({
     * 	"primary_key_columns": ["id"],
     * 	"totalCount": {"enabled": true},
     * 	"description": "Double entry transaction",
     * 	"foreign_keys": [
     * 		{
     *       "local_name": "transactions",
     *       "local_columns": ["account_id"],
     *       "foreign_name": "account",
     *       "foreign_schema": "public",
     *       "foreign_table": "account",
     *       "foreign_columns": ["id"]
     * 		}
     * 	]
     * })
     */
    public async create(request: Venice.CreateTransaction): Promise<void> {
        const { select, prefer, body: _body } = request;
        const _queryParams = new URLSearchParams();
        if (select != null) {
            _queryParams.append("select", select);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/transaction"),
            method: "POST",
            headers: {
                Prefer: prefer,
            },
            queryParameters: _queryParams,
            body: await serializers.Transaction.jsonOrThrow(_body),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * @graphql({
     * 	"primary_key_columns": ["id"],
     * 	"totalCount": {"enabled": true},
     * 	"description": "Double entry transaction",
     * 	"foreign_keys": [
     * 		{
     *       "local_name": "transactions",
     *       "local_columns": ["account_id"],
     *       "foreign_name": "account",
     *       "foreign_schema": "public",
     *       "foreign_table": "account",
     *       "foreign_columns": ["id"]
     * 		}
     * 	]
     * })
     */
    public async delete(request: Venice.DeleteTransaction = {}): Promise<void> {
        const {
            id,
            date,
            description,
            payee,
            amountQuantity,
            amountUnit,
            accountId,
            externalCategory,
            notes,
            splits,
            external,
            updatedAt,
            createdAt,
            prefer,
        } = request;
        const _queryParams = new URLSearchParams();
        if (id != null) {
            _queryParams.append("id", id);
        }

        if (date != null) {
            _queryParams.append("date", date);
        }

        if (description != null) {
            _queryParams.append("description", description);
        }

        if (payee != null) {
            _queryParams.append("payee", payee);
        }

        if (amountQuantity != null) {
            _queryParams.append("amount_quantity", amountQuantity);
        }

        if (amountUnit != null) {
            _queryParams.append("amount_unit", amountUnit);
        }

        if (accountId != null) {
            _queryParams.append("account_id", accountId);
        }

        if (externalCategory != null) {
            _queryParams.append("external_category", externalCategory);
        }

        if (notes != null) {
            _queryParams.append("notes", notes);
        }

        if (splits != null) {
            _queryParams.append("splits", splits);
        }

        if (external != null) {
            _queryParams.append("external", external);
        }

        if (updatedAt != null) {
            _queryParams.append("updated_at", updatedAt);
        }

        if (createdAt != null) {
            _queryParams.append("created_at", createdAt);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/transaction"),
            method: "DELETE",
            headers: {
                Prefer: prefer,
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * @graphql({
     * 	"primary_key_columns": ["id"],
     * 	"totalCount": {"enabled": true},
     * 	"description": "Double entry transaction",
     * 	"foreign_keys": [
     * 		{
     *       "local_name": "transactions",
     *       "local_columns": ["account_id"],
     *       "foreign_name": "account",
     *       "foreign_schema": "public",
     *       "foreign_table": "account",
     *       "foreign_columns": ["id"]
     * 		}
     * 	]
     * })
     */
    public async update(request: Venice.UpdateTransaction): Promise<void> {
        const {
            id,
            date,
            description,
            payee,
            amountQuantity,
            amountUnit,
            accountId,
            externalCategory,
            notes,
            splits,
            external,
            updatedAt,
            createdAt,
            prefer,
            body: _body,
        } = request;
        const _queryParams = new URLSearchParams();
        if (id != null) {
            _queryParams.append("id", id);
        }

        if (date != null) {
            _queryParams.append("date", date);
        }

        if (description != null) {
            _queryParams.append("description", description);
        }

        if (payee != null) {
            _queryParams.append("payee", payee);
        }

        if (amountQuantity != null) {
            _queryParams.append("amount_quantity", amountQuantity);
        }

        if (amountUnit != null) {
            _queryParams.append("amount_unit", amountUnit);
        }

        if (accountId != null) {
            _queryParams.append("account_id", accountId);
        }

        if (externalCategory != null) {
            _queryParams.append("external_category", externalCategory);
        }

        if (notes != null) {
            _queryParams.append("notes", notes);
        }

        if (splits != null) {
            _queryParams.append("splits", splits);
        }

        if (external != null) {
            _queryParams.append("external", external);
        }

        if (updatedAt != null) {
            _queryParams.append("updated_at", updatedAt);
        }

        if (createdAt != null) {
            _queryParams.append("created_at", createdAt);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/transaction"),
            method: "PATCH",
            headers: {
                Prefer: prefer,
            },
            queryParameters: _queryParams,
            body: await serializers.Transaction.jsonOrThrow(_body),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
