/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Entities summary
 *
 *   Entities description that
 *   spans
 *   multiple lines
 *
 *
 * 	@graphql({
 * 		"primary_key_columns": ["id", "key"],
 * 		"totalCount": {"enabled": true},
 * 		"foreign_keys": []
 * 	})
 *
 */
export interface TransactionSplit {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    transactionId?: string;
    key?: string;
    amountQuantity?: string;
    amountUnit?: string;
    accountId?: string;
    data?: unknown;
    updatedAt?: string;
    createdAt?: string;
}
