/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Venice } from "@fern-api/venice";

export interface GetTransaction {
    id?: string;
    date?: string;
    description?: string;
    payee?: string;
    amountQuantity?: string;
    amountUnit?: string;
    accountId?: string;
    externalCategory?: string;
    notes?: string;
    splits?: string;
    external?: string;
    updatedAt?: string;
    createdAt?: string;
    /**
     * Filtering Columns
     */
    select?: string;
    /**
     * Ordering
     */
    order?: string;
    /**
     * Limiting and Pagination
     */
    offset?: string;
    /**
     * Limiting and Pagination
     */
    limit?: string;
    /**
     * Limiting and Pagination
     */
    range?: string;
    /**
     * Limiting and Pagination
     */
    rangeUnit?: string;
    /**
     * Preference
     */
    prefer?: Venice.Count;
}
