/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import { Venice } from "@fern-api/venice";
import urlJoin from "url-join";
import * as core from "../../../../core";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Pipeline {
    interface Options {
        environment: environments.VeniceEnvironment | string;
    }
}

export class Pipeline {
    constructor(private readonly options: Pipeline.Options) {}

    public async get(request: Venice.GetPipeline = {}): Promise<Venice.Pipeline[]> {
        const {
            id,
            sourceId,
            sourceState,
            destinationId,
            destinationState,
            linkOptions,
            createdAt,
            updatedAt,
            lastSyncStartedAt,
            lastSyncCompletedAt,
            select,
            order,
            offset,
            limit,
            range,
            rangeUnit,
            prefer,
        } = request;
        const _queryParams = new URLSearchParams();
        if (id != null) {
            _queryParams.append("id", id);
        }

        if (sourceId != null) {
            _queryParams.append("source_id", sourceId);
        }

        if (sourceState != null) {
            _queryParams.append("source_state", sourceState);
        }

        if (destinationId != null) {
            _queryParams.append("destination_id", destinationId);
        }

        if (destinationState != null) {
            _queryParams.append("destination_state", destinationState);
        }

        if (linkOptions != null) {
            _queryParams.append("link_options", linkOptions);
        }

        if (createdAt != null) {
            _queryParams.append("created_at", createdAt);
        }

        if (updatedAt != null) {
            _queryParams.append("updated_at", updatedAt);
        }

        if (lastSyncStartedAt != null) {
            _queryParams.append("last_sync_started_at", lastSyncStartedAt);
        }

        if (lastSyncCompletedAt != null) {
            _queryParams.append("last_sync_completed_at", lastSyncCompletedAt);
        }

        if (select != null) {
            _queryParams.append("select", select);
        }

        if (order != null) {
            _queryParams.append("order", order);
        }

        if (offset != null) {
            _queryParams.append("offset", offset);
        }

        if (limit != null) {
            _queryParams.append("limit", limit);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/pipeline"),
            method: "GET",
            headers: {
                Range: range,
                "Range-Unit": rangeUnit,
                Prefer: prefer,
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.pipeline.get.Response.parseOrThrow(
                _response.body as serializers.pipeline.get.Response.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async create(request: Venice.CreatePipeline): Promise<void> {
        const { select, prefer, body: _body } = request;
        const _queryParams = new URLSearchParams();
        if (select != null) {
            _queryParams.append("select", select);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/pipeline"),
            method: "POST",
            headers: {
                Prefer: prefer,
            },
            queryParameters: _queryParams,
            body: await serializers.Pipeline.jsonOrThrow(_body),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async delete(request: Venice.DeletePipeline = {}): Promise<void> {
        const {
            id,
            sourceId,
            sourceState,
            destinationId,
            destinationState,
            linkOptions,
            createdAt,
            updatedAt,
            lastSyncStartedAt,
            lastSyncCompletedAt,
            prefer,
        } = request;
        const _queryParams = new URLSearchParams();
        if (id != null) {
            _queryParams.append("id", id);
        }

        if (sourceId != null) {
            _queryParams.append("source_id", sourceId);
        }

        if (sourceState != null) {
            _queryParams.append("source_state", sourceState);
        }

        if (destinationId != null) {
            _queryParams.append("destination_id", destinationId);
        }

        if (destinationState != null) {
            _queryParams.append("destination_state", destinationState);
        }

        if (linkOptions != null) {
            _queryParams.append("link_options", linkOptions);
        }

        if (createdAt != null) {
            _queryParams.append("created_at", createdAt);
        }

        if (updatedAt != null) {
            _queryParams.append("updated_at", updatedAt);
        }

        if (lastSyncStartedAt != null) {
            _queryParams.append("last_sync_started_at", lastSyncStartedAt);
        }

        if (lastSyncCompletedAt != null) {
            _queryParams.append("last_sync_completed_at", lastSyncCompletedAt);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/pipeline"),
            method: "DELETE",
            headers: {
                Prefer: prefer,
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async update(request: Venice.UpdatePipeline): Promise<void> {
        const {
            id,
            sourceId,
            sourceState,
            destinationId,
            destinationState,
            linkOptions,
            createdAt,
            updatedAt,
            lastSyncStartedAt,
            lastSyncCompletedAt,
            prefer,
            body: _body,
        } = request;
        const _queryParams = new URLSearchParams();
        if (id != null) {
            _queryParams.append("id", id);
        }

        if (sourceId != null) {
            _queryParams.append("source_id", sourceId);
        }

        if (sourceState != null) {
            _queryParams.append("source_state", sourceState);
        }

        if (destinationId != null) {
            _queryParams.append("destination_id", destinationId);
        }

        if (destinationState != null) {
            _queryParams.append("destination_state", destinationState);
        }

        if (linkOptions != null) {
            _queryParams.append("link_options", linkOptions);
        }

        if (createdAt != null) {
            _queryParams.append("created_at", createdAt);
        }

        if (updatedAt != null) {
            _queryParams.append("updated_at", updatedAt);
        }

        if (lastSyncStartedAt != null) {
            _queryParams.append("last_sync_started_at", lastSyncStartedAt);
        }

        if (lastSyncCompletedAt != null) {
            _queryParams.append("last_sync_completed_at", lastSyncCompletedAt);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/pipeline"),
            method: "PATCH",
            headers: {
                Prefer: prefer,
            },
            queryParameters: _queryParams,
            body: await serializers.Pipeline.jsonOrThrow(_body),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
