/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import { Venice } from "@fern-api/venice";
import urlJoin from "url-join";
import * as core from "../../../../core";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Resource {
    interface Options {
        environment: environments.VeniceEnvironment | string;
    }
}

export class Resource {
    constructor(private readonly options: Resource.Options) {}

    public async get(request: Venice.GetResource = {}): Promise<Venice.Resource[]> {
        const {
            id,
            creatorId,
            integrationId,
            institutionId,
            envName,
            settings,
            createdAt,
            updatedAt,
            providerName,
            displayName,
            select,
            order,
            offset,
            limit,
            range,
            rangeUnit,
            prefer,
        } = request;
        const _queryParams = new URLSearchParams();
        if (id != null) {
            _queryParams.append("id", id);
        }

        if (creatorId != null) {
            _queryParams.append("creator_id", creatorId);
        }

        if (integrationId != null) {
            _queryParams.append("integration_id", integrationId);
        }

        if (institutionId != null) {
            _queryParams.append("institution_id", institutionId);
        }

        if (envName != null) {
            _queryParams.append("env_name", envName);
        }

        if (settings != null) {
            _queryParams.append("settings", settings);
        }

        if (createdAt != null) {
            _queryParams.append("created_at", createdAt);
        }

        if (updatedAt != null) {
            _queryParams.append("updated_at", updatedAt);
        }

        if (providerName != null) {
            _queryParams.append("provider_name", providerName);
        }

        if (displayName != null) {
            _queryParams.append("display_name", displayName);
        }

        if (select != null) {
            _queryParams.append("select", select);
        }

        if (order != null) {
            _queryParams.append("order", order);
        }

        if (offset != null) {
            _queryParams.append("offset", offset);
        }

        if (limit != null) {
            _queryParams.append("limit", limit);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/resource"),
            method: "GET",
            headers: {
                Range: range,
                "Range-Unit": rangeUnit,
                Prefer: prefer,
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.resource.get.Response.parseOrThrow(
                _response.body as serializers.resource.get.Response.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async create(request: Venice.CreateResource): Promise<void> {
        const { select, prefer, body: _body } = request;
        const _queryParams = new URLSearchParams();
        if (select != null) {
            _queryParams.append("select", select);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/resource"),
            method: "POST",
            headers: {
                Prefer: prefer,
            },
            queryParameters: _queryParams,
            body: await serializers.Resource.jsonOrThrow(_body),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async delete(request: Venice.DeleteResource = {}): Promise<void> {
        const {
            id,
            creatorId,
            integrationId,
            institutionId,
            envName,
            settings,
            createdAt,
            updatedAt,
            providerName,
            displayName,
            prefer,
        } = request;
        const _queryParams = new URLSearchParams();
        if (id != null) {
            _queryParams.append("id", id);
        }

        if (creatorId != null) {
            _queryParams.append("creator_id", creatorId);
        }

        if (integrationId != null) {
            _queryParams.append("integration_id", integrationId);
        }

        if (institutionId != null) {
            _queryParams.append("institution_id", institutionId);
        }

        if (envName != null) {
            _queryParams.append("env_name", envName);
        }

        if (settings != null) {
            _queryParams.append("settings", settings);
        }

        if (createdAt != null) {
            _queryParams.append("created_at", createdAt);
        }

        if (updatedAt != null) {
            _queryParams.append("updated_at", updatedAt);
        }

        if (providerName != null) {
            _queryParams.append("provider_name", providerName);
        }

        if (displayName != null) {
            _queryParams.append("display_name", displayName);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/resource"),
            method: "DELETE",
            headers: {
                Prefer: prefer,
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async update(request: Venice.UpdateResource): Promise<void> {
        const {
            id,
            creatorId,
            integrationId,
            institutionId,
            envName,
            settings,
            createdAt,
            updatedAt,
            providerName,
            displayName,
            prefer,
            body: _body,
        } = request;
        const _queryParams = new URLSearchParams();
        if (id != null) {
            _queryParams.append("id", id);
        }

        if (creatorId != null) {
            _queryParams.append("creator_id", creatorId);
        }

        if (integrationId != null) {
            _queryParams.append("integration_id", integrationId);
        }

        if (institutionId != null) {
            _queryParams.append("institution_id", institutionId);
        }

        if (envName != null) {
            _queryParams.append("env_name", envName);
        }

        if (settings != null) {
            _queryParams.append("settings", settings);
        }

        if (createdAt != null) {
            _queryParams.append("created_at", createdAt);
        }

        if (updatedAt != null) {
            _queryParams.append("updated_at", updatedAt);
        }

        if (providerName != null) {
            _queryParams.append("provider_name", providerName);
        }

        if (displayName != null) {
            _queryParams.append("display_name", displayName);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/resource"),
            method: "PATCH",
            headers: {
                Prefer: prefer,
            },
            queryParameters: _queryParams,
            body: await serializers.Resource.jsonOrThrow(_body),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VeniceError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VeniceError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.VeniceTimeoutError();
            case "unknown":
                throw new errors.VeniceError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
