/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Venice } from "@fern-api/venice";

export interface DeleteRawTransaction {
    id?: string;
    sourceId?: string;
    standard?: string;
    external?: string;
    createdAt?: string;
    updatedAt?: string;
    providerName?: string;
    ledgerResourceId?: string;
    /**
     * Preference
     */
    prefer?: Venice.Return;
}
