/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Venice } from "@fern-api/venice";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.resource.get.Response.Raw, Venice.Resource[]> =
    core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Resource));

export declare namespace Response {
    type Raw = serializers.Resource.Raw[];
}
