/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Venice } from "@fern-api/venice";

export interface DeleteAccount {
    id?: string;
    name?: string;
    type?: string;
    lastFour?: string;
    institutionName?: string;
    defaultUnit?: string;
    currentBalance?: string;
    availableBalance?: string;
    external?: string;
    updatedAt?: string;
    createdAt?: string;
    /**
     * Preference
     */
    prefer?: Venice.Return;
}
