/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Venice } from "@fern-api/venice";

export interface GetAccount {
    id?: string;
    name?: string;
    type?: string;
    lastFour?: string;
    institutionName?: string;
    defaultUnit?: string;
    currentBalance?: string;
    availableBalance?: string;
    external?: string;
    updatedAt?: string;
    createdAt?: string;
    /**
     * Filtering Columns
     */
    select?: string;
    /**
     * Ordering
     */
    order?: string;
    /**
     * Limiting and Pagination
     */
    offset?: string;
    /**
     * Limiting and Pagination
     */
    limit?: string;
    /**
     * Limiting and Pagination
     */
    range?: string;
    /**
     * Limiting and Pagination
     */
    rangeUnit?: string;
    /**
     * Preference
     */
    prefer?: Venice.Count;
}
