/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Venice } from "@fern-api/venice";

export interface CreateIntegration {
    /**
     * Filtering Columns
     */
    select?: string;
    /**
     * Preference
     */
    prefer?: Venice.Return;
    body: Venice.Integration;
}
