/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @graphql({
 * 	"primary_key_columns": ["id"],
 * 	"totalCount": {"enabled": true},
 * 	"foreign_keys": []
 * })
 */
export interface Account {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id?: string;
    name?: string;
    type?: string;
    lastFour?: string;
    institutionName?: string;
    defaultUnit?: string;
    currentBalance?: number;
    availableBalance?: number;
    external?: unknown;
    updatedAt?: string;
    createdAt?: string;
}
