/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Institution {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    standard?: unknown;
    external?: unknown;
    createdAt: string;
    updatedAt: string;
    providerName: string;
}
