/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Integration {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    config?: unknown;
    createdAt: string;
    updatedAt: string;
    providerName: string;
}
