/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Pipeline {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `resource.id`.<fk table='resource' column='id'/>
     */
    sourceId?: string;
    sourceState?: unknown;
    /**
     * Note:
     * This is a Foreign Key to `resource.id`.<fk table='resource' column='id'/>
     */
    destinationId?: string;
    destinationState?: unknown;
    linkOptions?: unknown;
    createdAt: string;
    updatedAt: string;
    lastSyncStartedAt?: string;
    lastSyncCompletedAt?: string;
}
