/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Resource {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    creatorId?: string;
    /**
     * Note:
     * This is a Foreign Key to `integration.id`.<fk table='integration' column='id'/>
     */
    integrationId?: string;
    /**
     * Note:
     * This is a Foreign Key to `institution.id`.<fk table='institution' column='id'/>
     */
    institutionId?: string;
    envName?: string;
    settings?: unknown;
    createdAt: string;
    updatedAt: string;
    providerName: string;
    displayName?: string;
}
