/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Return =
    | "return=representation"
    | "return=minimal"
    | "return=none"
    | "resolution=ignore-duplicates"
    | "resolution=merge-duplicates";

export const Return = {
    Representation: "return=representation",
    Minimal: "return=minimal",
    None: "return=none",
    IgnoreDuplicates: "resolution=ignore-duplicates",
    MergeDuplicates: "resolution=merge-duplicates",
} as const;
