/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * TODO: Add description of transaction data type here...
 *
 * @graphql({
 * 	"primary_key_columns": ["id"],
 * 	"totalCount": {"enabled": true},
 * 	"description": "Double entry transaction",
 * 	"foreign_keys": [
 * 		{
 *       "local_name": "transactions",
 *       "local_columns": ["account_id"],
 *       "foreign_name": "account",
 *       "foreign_schema": "public",
 *       "foreign_table": "account",
 *       "foreign_columns": ["id"]
 * 		}
 * 	]
 * })
 */
export interface Transaction {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id?: string;
    date?: string;
    description?: string;
    payee?: string;
    amountQuantity?: number;
    amountUnit?: string;
    accountId?: string;
    externalCategory?: string;
    notes?: string;
    splits?: unknown;
    external?: unknown;
    updatedAt?: string;
    createdAt?: string;
}
