/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import { Introspection } from "./api/resources/introspection/client/Client";
import { Account } from "./api/resources/account/client/Client";
import { Institution } from "./api/resources/institution/client/Client";
import { Integration } from "./api/resources/integration/client/Client";
import { Pipeline } from "./api/resources/pipeline/client/Client";
import { RawAccount } from "./api/resources/rawAccount/client/Client";
import { RawCommodity } from "./api/resources/rawCommodity/client/Client";
import { RawTransaction } from "./api/resources/rawTransaction/client/Client";
import { Resource } from "./api/resources/resource/client/Client";
import { Transaction } from "./api/resources/transaction/client/Client";
import { TransactionSplit } from "./api/resources/transactionSplit/client/Client";

export declare namespace VeniceClient {
    interface Options {
        environment: environments.VeniceEnvironment | string;
    }
}

export class VeniceClient {
    constructor(private readonly options: VeniceClient.Options) {}

    private _introspection: Introspection | undefined;

    public get introspection(): Introspection {
        return (this._introspection ??= new Introspection(this.options));
    }

    private _account: Account | undefined;

    public get account(): Account {
        return (this._account ??= new Account(this.options));
    }

    private _institution: Institution | undefined;

    public get institution(): Institution {
        return (this._institution ??= new Institution(this.options));
    }

    private _integration: Integration | undefined;

    public get integration(): Integration {
        return (this._integration ??= new Integration(this.options));
    }

    private _pipeline: Pipeline | undefined;

    public get pipeline(): Pipeline {
        return (this._pipeline ??= new Pipeline(this.options));
    }

    private _rawAccount: RawAccount | undefined;

    public get rawAccount(): RawAccount {
        return (this._rawAccount ??= new RawAccount(this.options));
    }

    private _rawCommodity: RawCommodity | undefined;

    public get rawCommodity(): RawCommodity {
        return (this._rawCommodity ??= new RawCommodity(this.options));
    }

    private _rawTransaction: RawTransaction | undefined;

    public get rawTransaction(): RawTransaction {
        return (this._rawTransaction ??= new RawTransaction(this.options));
    }

    private _resource: Resource | undefined;

    public get resource(): Resource {
        return (this._resource ??= new Resource(this.options));
    }

    private _transaction: Transaction | undefined;

    public get transaction(): Transaction {
        return (this._transaction ??= new Transaction(this.options));
    }

    private _transactionSplit: TransactionSplit | undefined;

    public get transactionSplit(): TransactionSplit {
        return (this._transactionSplit ??= new TransactionSplit(this.options));
    }
}
