/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const VeniceEnvironment = {
    Dev: "http://development.venice.local:3000/api/rest",
} as const;

export type VeniceEnvironment = typeof VeniceEnvironment.Dev;
