/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Venice } from "@fern-api/venice";
import * as core from "../../../../core";

export const Count: core.serialization.Schema<serializers.Count.Raw, Venice.Count> = core.serialization.enum_([
    "count=none",
]);

export declare namespace Count {
    type Raw = "count=none";
}
