/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Venice } from "@fern-api/venice";
import * as core from "../../../../core";

export const Institution: core.serialization.ObjectSchema<serializers.Institution.Raw, Venice.Institution> =
    core.serialization.object({
        id: core.serialization.string(),
        standard: core.serialization.unknown(),
        external: core.serialization.unknown(),
        createdAt: core.serialization.property("created_at", core.serialization.string()),
        updatedAt: core.serialization.property("updated_at", core.serialization.string()),
        providerName: core.serialization.property("provider_name", core.serialization.string()),
    });

export declare namespace Institution {
    interface Raw {
        id: string;
        standard?: unknown;
        external?: unknown;
        created_at: string;
        updated_at: string;
        provider_name: string;
    }
}
