/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Venice } from "@fern-api/venice";
import * as core from "../../../../core";

export const Integration: core.serialization.ObjectSchema<serializers.Integration.Raw, Venice.Integration> =
    core.serialization.object({
        id: core.serialization.string(),
        config: core.serialization.unknown(),
        createdAt: core.serialization.property("created_at", core.serialization.string()),
        updatedAt: core.serialization.property("updated_at", core.serialization.string()),
        providerName: core.serialization.property("provider_name", core.serialization.string()),
    });

export declare namespace Integration {
    interface Raw {
        id: string;
        config?: unknown;
        created_at: string;
        updated_at: string;
        provider_name: string;
    }
}
