/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Venice } from "@fern-api/venice";
import * as core from "../../../../core";

export const Return: core.serialization.Schema<serializers.Return.Raw, Venice.Return> = core.serialization.enum_([
    "return=representation",
    "return=minimal",
    "return=none",
    "resolution=ignore-duplicates",
    "resolution=merge-duplicates",
]);

export declare namespace Return {
    type Raw =
        | "return=representation"
        | "return=minimal"
        | "return=none"
        | "resolution=ignore-duplicates"
        | "resolution=merge-duplicates";
}
